# Generated by Django 3.2.5 on 2021-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('emaiid', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=20)),
                ('mobilenum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('emaiid', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=20)),
                ('mobilenum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('emaiid', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=20)),
                ('mobilenum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='selected_paper',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Topic', models.CharField(max_length=20)),
                ('Url', models.URLField()),
                ('Department', models.CharField(max_length=20)),
                ('emaiid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='submitted_papers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Topic', models.CharField(max_length=20)),
                ('Url', models.URLField()),
                ('Department', models.CharField(max_length=20)),
                ('emaiid', models.CharField(max_length=50)),
            ],
        ),
    ]
