# Generated by Django 3.2.5 on 2021-09-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210918_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_paper',
            name='Reviewer',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
