# Generated by Django 3.2.5 on 2021-09-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_returned_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='amountpaid',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
