# Generated by Django 3.2.5 on 2021-09-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210920_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='paid',
            field=models.CharField(max_length=10),
        ),
    ]
