# Generated by Django 3.2.5 on 2021-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_paymentdetails_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewed_papers',
            name='comment',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
