# Generated by Django 3.2.5 on 2021-09-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reviewed_papers_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewed_papers',
            name='comment',
        ),
    ]
